### ISSUE TITLE
EayunOS 4.1 安装完成之后重启可能会出现启动失败的情况

### ISSUE THREAD

**Issue by zhaochao** [eayun/EayunOS-building#21]
启动失败时，出现的错误信息如下：
dracut-initqueue[371]: mount: /dev/sda3 is already mounted or /run/initramfs/live busy
[    1.134548] dracut: Fatal: Failed to mount block device of live image
[    1.134554] dracut: Refusing to continue
[    1.135073] dracut: System halted.

**Comment by walteryang47** [comment]
closed as version published
